# Generated by Django 5.2.17 on 2026-09-14 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('host_session', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('LOBBY', 'Lobby'), ('FASTEST_FINGER', 'Fastest Finger'), ('QUESTION_ACTIVE', 'Question Active'), ('ANSWER_LOCKED', 'Answer Locked'), ('REVEAL', 'Reveal'), ('LEADERBOARD', 'Leaderboard'), ('FINAL', 'Final'), ('GAME_OVER', 'Game Over'), ('PAUSED', 'Paused')], default='LOBBY', max_length=32)),
                ('current_question_number', models.PositiveSmallIntegerField(default=0)),
                ('total_questions', models.PositiveSmallIntegerField(default=15)),
                ('timer_seconds', models.PositiveSmallIntegerField(default=15)),
                ('question_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('category', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('EXPERT', 'Expert'), ('VERY_HARD', 'Very Hard')], max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudiencePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('game_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='game.gamequestion')),
            ],
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_questions', to='game.gameroom'),
        ),
        migrations.CreateModel(
            name='FastestFingerRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fastest_round', to='game.gameroom')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80)),
                ('session_id', models.UUIDField(default=uuid.uuid4)),
                ('current_prize', models.PositiveBigIntegerField(default=0)),
                ('secured_prize', models.PositiveBigIntegerField(default=0)),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('answered_questions', models.PositiveSmallIntegerField(default=0)),
                ('missed_questions', models.PositiveSmallIntegerField(default=0)),
                ('total_response_time_ms', models.PositiveBigIntegerField(default=0)),
                ('lifelines', models.JSONField(default=dict)),
                ('connected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.gameroom')),
            ],
        ),
        migrations.CreateModel(
            name='LifelineUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifeline', models.CharField(max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamequestion')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifeline_uses', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='FastestFingerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_answer', models.JSONField()),
                ('submitted_at', models.DateTimeField()),
                ('is_correct', models.BooleanField(default=False)),
                ('response_time_ms', models.PositiveIntegerField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='game.fastestfingerround')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_option', models.CharField(blank=True, max_length=1, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_requests', to='game.gamequestion')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_requests_received', to='game.player')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_requests_made', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='AudienceVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='game.audiencepoll')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.AddField(
            model_name='audiencepoll',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls_requested', to='game.player'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('attempts', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('missed', models.BooleanField(default=False)),
                ('game_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.gamequestion')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.player')),
            ],
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.question'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('room', 'session_id'), name='unique_player_session'),
        ),
        migrations.AddConstraint(
            model_name='audiencevote',
            constraint=models.UniqueConstraint(fields=('poll', 'voter'), name='unique_poll_voter'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('game_question', 'player'), name='unique_answer'),
        ),
        migrations.AddConstraint(
            model_name='gamequestion',
            constraint=models.UniqueConstraint(fields=('room', 'sequence'), name='unique_room_sequence'),
        ),
    ]
